version: '3.8'
services:
  dhapi-lotto:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Seoul
      - DH_USERNAME=${DH_USERNAME}
      - DH_PASSWORD=${DH_PASSWORD}
      - LOTTO_NUMBERS=${LOTTO_NUMBERS}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_TO=${EMAIL_TO}
    volumes:
      - ./output:/app/output